In [1]:
import numpy as np
def gs(A):
 A=np.array(A,float)
 m,n=A.shape
 Q=np.zeros((m,n))
 R=np.zeros((n,n))
 for j in range(n):
  v=A[:,j].copy()
  for i in range(j):
   R[i,j]=Q[:,i].dot(A[:,j])
   v=v-R[i,j]*Q[:,i]
  R[j,j]=np.linalg.norm(v)
  if R[j,j]==0:
   Q[:,j]=v
  else:
   Q[:,j]=v/R[j,j]
 return Q,R

if __name__=="__main__":
 q,r=gs([[1,1],[1,2],[1,3]])
 print(q)
 print(r)
"""[[ 5.77350269e-01 -7.07106781e-01]
 [ 5.77350269e-01 -3.14018492e-16]
 [ 5.77350269e-01  7.07106781e-01]]
[[1.73205081 3.46410162]
 [0.         1.41421356]]"""


[[ 5.77350269e-01 -7.07106781e-01]
 [ 5.77350269e-01 -3.14018492e-16]
 [ 5.77350269e-01  7.07106781e-01]]
[[1.73205081 3.46410162]
 [0.         1.41421356]]
